# 注意: 关于预习题是否需要打印，存在不同贡献者的矛盾信息，请以最新学期为准。
course_name = "数字电子技术实验"
course_code = "EE1010"
notices = ""

[[lecturers]]
name = "实验中心教师、理论课教师、本科生助教"
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

textbooks = []

[[online_resources]]
title = "Verilog 教程"
url = "https://www.runoob.com/w3cnote/verilog-tutorial.html"
description = "课程推荐的 Verilog 预习教程。"
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

course = []

[[exam]]
content = "没有考试"
author = { name = "", link = "", date = "" }

lab = []

[[advice]]
content = """
听课建议：先讲一小会儿原理和注意事项（需要听一下，因为有些器材的使用方法不那么直观）。然后就自己做实验，有问题可以问助教。
上课前，需要完成预习题并打印出纸质版。需要当堂检查，不要在课上补。
六次实验，每次实验是 4 学时，任务量比较大。
  - 对于硬件实验（利用 74 系列中规模集成芯片完成的实验），主要考查的是细心程度。
    - 上课前就设计好电路，并仔细分析其正确性，边上课边搭建电路大概率不能按时完成。
    - 有同学接线时候贪快，总是接错线，到最后总要在密密麻麻的线里面找错误，这是非常费时费力的。做很多事情都是这样，与其犯了错误事后缝缝补补，不如一开始就耐住性子认真做好。
  - 对于软硬件结合的实验（利用 Verilog 语言 + FPGA 实现逻辑电路），由于课上能学习 Verilog 的时间很少（基本都要用来完成任务），讲解的 Verilog 语法也很有限，大家在上数字电子技术实验有关 Verilog 的内容前，务必认真预习！
实验报告在 Easy 云课堂（微信小程序或网页端）网上提交，无需提交纸质版。电脑版建议使用网页端。
"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

[[advice]]
content = "2024 春的数电实验在上课前已经不需要打印纸质版预习题，但仍需在 Easy 云课堂上完成预习题后方可看到当次实验的具体内容（实验任务、指导书、教学视频等）"
author = { name = "psp_dada", link = "https://github.com/pspdada", date = "" }

schedule = []

[[related_links]]
content = "https://github.com/MaxwellJay256/FPGALab_2024"
author = { name = "", link = "", date = "" }

misc = []