# 贡献者 @psp_dada 的信息更新（关于预习题）与 @Oliver Wu 的原始信息存在冲突，已将最新信息置于 notices 板块，并相应调整了 advice 板块的内容。
course_name = "数字电子技术实验"
course_code = "EE1010"

notices = """2024 春的数电实验在上课前已经不需要打印纸质版预习题，但仍需在 Easy 云课堂上完成预习题后方可看到当次实验的具体内容（实验任务、指导书、教学视频等）。"""

[[lecturers]]
name = "实验中心教师+（部分班级）理论课教师+二名本科生助教"
reviews = []
[lecturers.author]
name = "Oliver Wu"
link = "https://github.com/OliverWu515"
date = ""

textbooks = []

[[online_resources]]
title = "Verilog 教程"
url = "https://www.runoob.com/w3cnote/verilog-tutorial.html"
description = "推荐用于预习软硬件结合的实验（利用 Verilog 语言 + FPGA 实现逻辑电路）的内容。"
[online_resources.author]
name = "Oliver Wu"
link = "https://github.com/OliverWu515"
date = ""

[[course]]
content = "课程包含六次实验，分为硬件实验（利用 74 系列中规模集成芯片）和软硬件结合的实验（利用 Verilog 语言 + FPGA）。"
[course.author]
name = "Oliver Wu"
link = "https://github.com/OliverWu515"
date = ""

[[exam]]
content = "没有考试。"
[exam.author]
name = ""
link = ""
date = ""

[[advice]]
content = """听课建议：先讲一小会儿原理和注意事项（需要听一下，因为有些器材的使用方法不那么直观）。然后就自己做实验，有问题可以问助教。
上课前，需要完成预习题。
对于硬件实验（利用 74 系列中规模集成芯片完成的实验），主要考查的是细心程度。上课前就设计好电路，并仔细分析其正确性，边上课边搭建电路大概率不能按时完成。有同学接线时候贪快，总是接错线，到最后总要在密密麻麻的线里面找错误，这是非常费时费力的。做很多事情都是这样，与其犯了错误事后缝缝补补，不如一开始就耐住性子认真做好。
对于软硬件结合的实验（利用 Verilog 语言 + FPGA 实现逻辑电路），由于课上能学习 Verilog 的时间很少（基本都要用来完成任务），讲解的 Verilog 语法也很有限，大家在上数字电子技术实验有关 Verilog 的内容前，务必认真预习！"""
[advice.author]
name = "Oliver Wu"
link = "https://github.com/OliverWu515"
date = ""

[[schedule]]
content = "六次实验，每次实验是 4 学时，任务量比较大。"
[schedule.author]
name = "Oliver Wu"
link = "https://github.com/OliverWu515"
date = ""

[[related_links]]
content = "https://github.com/MaxwellJay256/FPGALab_2024"
[related_links.author]
name = ""
link = ""
date = ""

[[misc]]
content = "分数构成：预习题 + 按时完成实验（不按时完成，则适当扣分）+ 报告分数。"
[misc.author]
name = ""
link = ""
date = ""

[[misc]]
content = "实验报告在 Easy 云课堂（微信小程序或网页端）网上提交，无需提交纸质版。电脑版建议使用网页端。"
[misc.author]
name = "Oliver Wu"
link = "https://github.com/OliverWu515"
date = ""